---

- name: collectd-configure | Configure Collectd
  template: src=collectd.conf.j2 dest={{collectd_config_file}} validate='{{collectd_sbin_path}}/collectd -t -C %s'
  notify: collectd restart

- name: collectd-configure | Ensure conf.d directory
  file: path={{collectd_config_dir}} state=directory

- name: collectd-configure | Configure additional types
  template: src=types.db.j2 dest={{collectd_additional_types_db_path}}
  notify: collectd restart

- name: collectd-configure | Configure Addiotnal Plugin AMQP
  template: src=amqp.conf.j2 dest={{collectd_config_dir}}/amqp.conf validate='{{collectd_sbin_path}}/collectd -t -C %s'
  notify: collectd restart

- name: collectd-configure | Configure Additional Plugin NUMA CPU Aggregation
  template: src=numa_cpu_aggregation.conf.j2 dest={{collectd_config_dir}}/numa_cpu_aggregation.conf validate='{{collectd_sbin_path}}/collectd -t -C %s'
  notify: collectd restart
  
- name: collectd-configure | Configure Additional Plugin Docker Stats 1 of 3
  git: 
    dest: /usr/share/collectd/docker-collectd-plugin
    repo: "https://github.com/lebauce/docker-collectd-plugin.git"
  when: docker_stats


- name: collectd-configure | Configure Additional Plugin Docker Stats 2 of 3
  shell: pip install -r /usr/share/collectd/docker-collectd-plugin/requirements.txt
  notify: collectd restart
  when: docker_stats


- name: collectd-configure | Configure Additional Plugin Docker Stats 3 of 3
  template: src=docker.conf.j2 dest={{collectd_config_dir}}/docker.conf validate='{{collectd_sbin_path}}/collectd -t -C %s'
  notify: collectd restart
  when: docker_stats