---

- name: collectd-configure | Configure Collectd
  template: src=collectd.conf.j2 mode={{collectd_config_file_mode}} dest={{collectd_config_file}} validate='{{collectd_sbin_path}}/collectd -t -C %s'
  notify: collectd restart

- name: collectd-configure | Ensure conf.d directory
  file: path={{collectd_config_dir}} state=directory

- name: collectd-configure | Configure additional types
  template: src=types.db.j2 dest={{collectd_additional_types_db_path}}
  notify: collectd restart
