---

#TODO, to change 
#- name: fail, to change
#  fail:
#    msg:  TODO test manual installation

- name: collectd-install | Install dependencies
  package: name={{item}} state=present
  with_items: "{{ collectd_source_packages }}"

- name: collectd-install | Download Collectd
  get_url: url=http://collectd.org/files/collectd-{{collectd_version}}.tar.bz2 dest=/usr/src
  register: collectd_source

- name: collectd-install | Extract Collectd
  unarchive: src=/usr/src/collectd-{{collectd_version}}.tar.bz2 dest=/usr/src copy=no
  when: collectd_source.changed

- name: collectd-install | Install Collectd
  shell: ./configure --prefix={{collectd_prefix}} && make all install
  args:
    chdir: /usr/src/collectd-{{collectd_version}}
    creates: "{{collectd_prefix}}"
  when: collectd_source.changed
