---

- name: collectd-install | Install dependencies
  apt: name={{item}} force=yes
  with_items: [build-essential, libcurl4-openssl-dev, libpcap-dev, libyajl-dev, flex, bison, pkg-config, automake]

- name: collectd-install | Download Collectd
  git:
    dest: "{{ collectd_prefix_git_src }}"
    repo: "https://github.com/collectd/collectd.git"
  become: yes
  register: collectd_source

- name: collectd-install | Install Collectd
  shell: ./build.sh && ./configure --prefix={{collectd_prefix}} &&  make && make all install
  args:
    chdir: "{{ collectd_prefix_git_src }}"
  # when: collectd_source.changed
  become: yes

- name: collectd-install | Create /etc/init.d/collectd
  template: src=initd.collectd.j2 dest=/etc/init.d/collectd
  become: yes

- name: collectd-install | create run/collectd.pid file  
  shell: mkdir -p "{{collectd_prefix}}/run"
  becom: yes


- name: collectd-install | make it executable /etc/init.d/collectd
  shell: chmod +x /etc/init.d/collectd
  become: yes

- name: collectd-install | Enable collectd.service
  shell: systemctl enable collectd.service
  become: yes

- name: collectd-install | start the collectd.service 
  service: name=collectd state=started enabled=yes
  become: yes
