---

- name: collectd-install | Install ppa
  apt_repository: >
    repo={{ collectd_ppa_source }}
    update_cache=yes
  when: not collectd_use_ppa_ci 

- name: collectd-install | add signing key 
  apt_repository:
    repo: deb http://pkg.ci.collectd.org/deb/ {{ansible_distribution_release}} {{collectd_use_ppa_ci_codename}}
    state: present
    filename: collectd-ci.list
    update_cache: yes
  when: collectd_use_ppa_ci 
  

- name: collectd-install | add signing key
  apt_key:
    url: "http://pkg.ci.collectd.org/pubkey.asc"
    state: present
  when: collectd_use_ppa_ci 

- name: collectd-install | Install specific collectd package
  apt: >
    name=collectd={{ collectd_version }}
  when: not collectd_use_ppa_latest

- name: collectd-install | Install latest collectd minimal package
  apt: name=collectd
       install_recommends=no
  when: collectd_use_ppa_latest and collectd_use_ppa_minimal

- name: collectd-install | Install latest collectd package
  apt: name=collectd
  when: collectd_use_ppa_latest and not collectd_use_ppa_minimal
